### ISSUE TITLE
Structural Hole Calculation for Directed Graph

### ISSUE THREAD

**Issue by skyerguo** [easy-graph/Easy-Graph#100]
- [x] I have searched the [issues](https://github.com/easy-graph/Easy-Graph/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://easy-graph.github.io/) and believe that my question is not covered.

## Feature Request

The calculation of Effective Size(a feature of structural hole theory) only supports the undirected graphs. However, I think this metric is also useful for directed graphs. The "networkx" package has supported this by "networkx.effective_size".
I propose this issue for requesting the calculation support of structural hole theory metrics for directed graphs. Thanks!

**Comment by mgao97** [comment]
Good idea! Thank you, we will add it in the next version.
