### ISSUE TITLE
Add the time complexities

### ISSUE THREAD

**Issue by skyerguo** [easy-graph/Easy-Graph#101]
- [x] I have searched the [issues](https://github.com/easy-graph/Easy-Graph/issues) of this repo and believe that this is not a duplicate.

## Issue

I am wondering if you can add the calculation complexity (something like O(N^2)) in the documentation.
It would provide programmers with more information about how to pick an appropriate function.

**Comment by mgao97** [comment]
Got it! We will add it soon!

**Comment by tddschn** [comment]
@skyerguo @mgao97   
I'm working on this task - a few quick questions  
- There are so many functions and methods, where do I start?
- Should I just add the time complexities in the function docstrings?

**Comment by tddschn** [comment]
See https://github.com/tddschn/easygraph-function-time-complexities .

More are coming!
