### ISSUE TITLE
Support functions with parellel running and better use more cores of CPU

### ISSUE THREAD

**Issue by skyerguo** [easy-graph/Easy-Graph#102]
- [x] I have searched the [issues](https://github.com/easy-graph/Easy-Graph/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://easy-graph.github.io/) and believe that my question is not covered.

## Issue

I just used the function "eg.functions.not_sorted.pagerank" to calculate the pageranks of a graph, with about 50,000 nodes.
It runs a long time, and I check the system status using the command "htop". It shows that the calculation only uses one core of CPU, and wastes all other CPU cores. So I propose the issue, hope for parallel running characteristics and better usage of more CPU cores.

**Comment by Unparalleled-Calvin** [comment]
Thank you for your contribution to EasyGraph!
We notice that pagerank uses `numpy.linalg.eig` to compute eigenvalues and eigenvectors of the adjacency matrix. The method is inefficient as your issue denotes.
Possible improvement is to replace `numpy.linalg.eig` with a high performance matrix computing method. We will try to improve it then.
