### ISSUE TITLE
Support for creating graph object with node attrs. and edge attrs.

### ISSUE THREAD

**Issue by mgao97** [easy-graph/Easy-Graph#103]
- [ ] I have searched the [issues](https://github.com/easy-graph/Easy-Graph/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://easy-graph.github.io/) and believe that my question is not covered.

## Feature Request

1. Hi all, I am a little curious about the support for creating graph objects with node attributes and edge attributes.
2. Does EasyGraph support other graph types such as dynamic graphs and some high-order networks, such as hypergraphs?

Thanks a lot!

**Comment by tddschn** [comment]
1. `eg.Graph` supports creating graph object with node attrs. and edge attrs.
2. Hypergraphs are supported via `eg.Hypergraph`.
