### ISSUE TITLE
Impressed by your project!!!

### ISSUE THREAD

**Issue by xingshuohan** [easy-graph/Easy-Graph#134]
I recently started using this and I'm thoroughly impressed! The documentation is exceptionally clear and made it easy for me to get started. The API is intuitive, allowing me to integrate complex graph operations into my project. 

Thank much for the passionate team behind this project, so excited to see how Easy-Graph evolves and looking forward to contributing to the community. 

Anyway, great work!

**Comment by mgao97** [comment]
Thank you very much for your comments and you are very welcome to join us and contribute to the community!
