### ISSUE TITLE
the performance of using this library in python

### ISSUE THREAD

**Issue by Decade-rider** [easy-graph/Easy-Graph#136]
Can you please tell me how is the performance of using this library in python when I have a larger network right now, the size is roughly 200,000 nodes and 900,000 edges. And is there any advantage of this library over igraph?

**Comment by mgao97** [comment]
Hi! Thanks for your interest in our project!

Regarding the performance, our library performs well with large networks and can effectively execute representative network analysis algorithms. The detailed advantages could be referred to in our paper: https://www.cell.com/patterns/pdf/S2666-3899(23)00218-0.pdf

If you have any other questions or need further assistance, please feel free to reach out to us!
