### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by tddschn** [easy-graph/Easy-Graph#43]
By [GitHub convention](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), the CONTRIBUTING file specifies the guidelines for contribution, which allows more potential collabrators to contribute to `EasyGraph`.

Example outline of the CONTRIBUTING file:

- Coding style (e.g. PEP8) and the formatter to use (`yapf`, `black`, `autopep8`)
- Issue labeling rules
- Ways to contribute

Also consider adding a Code of Conduct file if this repo becomes popular. :)

**Comment by coreturn** [comment]
I agree with you, the doc can really get better.

**Comment by tddschn** [comment]
Added file https://github.com/easy-graph/Easy-Graph/blob/master/CONTRIBUTING.md
