### ISSUE TITLE
Set up CI to test across different python versions and operating systems

### ISSUE THREAD

**Issue by tddschn** [easy-graph/Easy-Graph#45]
To ensure the changes made don't break existing features, it's a good practice to set up CI run on that is triggered every pull requrests and commit to the master branch, for automated testing across all supported python versions and operating systems. Commits to `master` will be blocked until all the tests have passed.

See [this guide](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python) for Building and testing Python on GitHub Actions.

Questions:
- How much test coverage are we looking at here?
- What features requires more attention and tests?
- Testing framework to use? (`pytest`, `unittest`)
- How do we test and keep track of the performance of the functions? Do we compare the perfs with that of popular libraries?
- How do we test ML related features like graph embedding in a deterministic way so that the test case runs produce the same results?

**Comment by coreturn** [comment]
I agree with you. CI is necessary.🤔

**Comment by coreturn** [comment]
Of course, we hope to cover as many methods as possible. But for the limited time, we will cover the incremental methods first. Then for the methods that already exist, we will focused on structural holes algorithm first which is our VIP. It's really not easy to test ML, so maybe we just need to take some tests to ensure the correctness of critical parts.
