### ISSUE TITLE
Proposal: Adopt a Git Workflow

### ISSUE THREAD

**Issue by tddschn** [easy-graph/Easy-Graph#46]
I think it'd be beneficial to adopt a git workflow, 
e.g. constantly pushing to `dev` branch and only periodically merging `dev` into `master`.

`master` is always stable and won't break for the end users.

Commits on `master` can also be set up to trigger an automatic release to PyPI & conda, via CI pipelines.

**Comment by coreturn** [comment]
I agree with you, the master is safer.
