### ISSUE TITLE
Add PyPI API key in repo settings for CI

### ISSUE THREAD

**Issue by tddschn** [easy-graph/Easy-Graph#49]
## Who should do it?

The person controlling EasyGraph package on PyPI and the creator of GitHub org `easy-graph`, who's probably @ICYPOLE.

## Steps to take:

Go to https://pypi.org/manage/account/#api-tokens and create a new API token. If you have the project on PyPI already, limit the token scope to just that project. You can call it something like GitHub Actions CI/CD — project-org/project-repo in order for it to be easily distinguishable in the token list. Don’t close the page just yet — you won’t see that token again.

In a separate browser tab or window, go to the Settings tab of your target repository and then click on Secrets in the left sidebar.

Create a new secret called PYPI_API_TOKEN and copy-paste the token from the first step.

**Comment by coreturn** [comment]
Thanks, this work is expected to be done today.

**Comment by coreturn** [comment]
Already done, You can try again, if there are problems, continue to discuss in this issue.
