### ISSUE TITLE
Skipgram parameter needs to be renamed

### ISSUE THREAD

**Issue by ngiatsog** [easy-graph/Easy-Graph#61]
Having installed Easy-Graph with the dependency Gensim>=4.1.2, the execution failed outputting that the Gensim Word2Vec class could not recognize the skipgram argument "size". Digging around, I found that the learn_embeddings() function (link below) inserts the  keyword 'size' in skip_gram_params, although the Gensim Word2Vec class requires a 'vector_size' argument. The parameter must be renamed to solve the issue.

https://github.com/easy-graph/Easy-Graph/blob/2cd69126dd25d71f538ed4709518dd37838e5b54/easygraph/functions/graph_embedding/node2vec.py#L269

**Comment by coreturn** [comment]
Thank for your feedback, we will fix this in the next release.

**Comment by tddschn** [comment]
@ngiatsog  

Sorry for the delayed reply.

I implemented your suggested fix 7 months ago, and here's how it looks like now:
https://github.com/easy-graph/Easy-Graph/blob/f642b3d3f5376ec69f3f3c773ebf0e35a9f0ae6c/easygraph/functions/graph_embedding/node2vec.py#L304

Does this fix your issue?
