### ISSUE TITLE
Santized charset used in files

### ISSUE THREAD

**Issue by tddschn** [easy-graph/Easy-Graph#78]
The comments in the `.cpp` and `.h` files are shown as garbled text on machines using UTF-8 charset.

@Unparalleled-Calvin Can you fix them? I'd love to be able to read your comments. :)

<img width="970" alt="CleanShot-2022-06-30T13-44-42@2x" src="https://user-images.githubusercontent.com/45612704/176602924-f9b26375-18ef-4216-87f9-742429973b25.png">

**Comment by tddschn** [comment]
<img width="970" alt="CleanShot-2022-06-30T13-44-42@2x" src="https://user-images.githubusercontent.com/45612704/176602965-53fb971f-ecb4-43e8-b8d7-9dba2f4cdc51.png">

**Comment by Unparalleled-Calvin** [comment]
I suppose that charset GBK which VS uses by default causes this problem. I will fix it in my next submission.
