### ISSUE TITLE
Paramemters not used in function hierarchy

### ISSUE THREAD

**Issue by Unparalleled-Calvin** [easy-graph/Easy-Graph#83]
![image](https://user-images.githubusercontent.com/72065302/180223178-cbd45c36-449e-4b9f-87ce-1acfd51f11c8.png)
parameter nodes and weight are not used. please fix the problem.

**Comment by tddschn** [comment]
Has this been fixed?

**Comment by Unparalleled-Calvin** [comment]
yes
