### ISSUE TITLE
Input type of source node in Dijkstra

### ISSUE THREAD

**Issue by puffy-cavy** [easy-graph/Easy-Graph#91]
[easygraph](https://github.com/easy-graph/Easy-Graph/tree/master/easygraph)/[functions](https://github.com/easy-graph/Easy-Graph/tree/master/easygraph/functions)/[path](https://github.com/easy-graph/Easy-Graph/tree/master/easygraph/functions/path/path.py/)
## Issue

the annotation of Dijkstra function need to be updated:  
the source node could be any type that is hashable, if the graph is created by add_edges_from_file(), the type of source_node() should be string

**Comment by tddschn** [comment]
fixed: https://github.com/easy-graph/Easy-Graph/blob/b4c62fe48047bfa2b75f5e639e038f9473548114/easygraph/functions/path/path.py#L31
