### ISSUE TITLE
Slow performance on Structural Holes

### ISSUE THREAD

**Issue by aritan7** [easy-graph/Easy-Graph#95]
- [x] I have searched the [issues](https://github.com/easy-graph/Easy-Graph/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://easy-graph.github.io/) and believe that my question is not covered.

## Version 
0.2a39, Installed through pypi and Linux Script in repo. Tested using Ubuntu 20.04 TLS

## Issue

For HITS AND MAX-D structural holes, it took forever to return results of a large graph  with 80K relationships. 
Is there any way to speed up the performance? This is because only single core is used as processing at a time.

Source data: https://github.com/aritan7/pgraph/raw/main/node10k.csv

```
import easygraph as eg
from easygraph.functions.community.modularity_max_detection import *
G = eg.Graph()
G.add_edges_from_file(file='node10k.csv')
c = eg.greedy_modularity_communities(G)
maxd = eg.get_structural_holes_MaxD(G,k=50, C=c)
```

**Update:** 
1. Using **get_structural_holes_HIS()** would cause a memory leak.

**Comment by tddschn** [comment]
Sorry for the slow response. The current version on PyPI is very outdated, we'll push the latest version as soon as we figure out how to integrate the C++ binding framework we use with our CI pipeline.

In the meantime, here's a work around you can try to install the latest version of easygraph on your machine:

```bash
git clone https://github.com/easy-graph/Easy-Graph && cd Easy-Graph
pip install pybind11
python3 setup.py install
```

**Comment by ayaanhossain** [comment]
Even if there is some issue on the CI side of things, you can still push the latest version on PyPI. From the workaround illustrated, one just needs to make `pybind11` a part of `setup_requires` (not `install_requires`), and everything should be good to go?
